// <auto-generated />
using System;
using IndustrialMonitor.DBAcess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndustrialMonitor.DBAcess.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20260715105449_RemoveTrendConfiguration")]
    partial class RemoveTrendConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IndustrialMonitor.DataEntities.DeviceEntity", b =>
                {
                    b.Property<string>("DeviceNum")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DeviceNum");

                    b.ToTable("monitor_Devices");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.DevicePropEntity", b =>
                {
                    b.Property<int>("DevicePropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DevicePropId"));

                    b.Property<string>("DeviceNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PropName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PropValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DevicePropId");

                    b.ToTable("monitor_DeviceProps");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.DeviceVarEntity", b =>
                {
                    b.Property<string>("VarNum")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DeviceNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Modulus")
                        .HasColumnType("double");

                    b.Property<double>("Offset")
                        .HasColumnType("double");

                    b.Property<string>("VarAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VarName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VarType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("VarNum");

                    b.ToTable("monitor_DeviceVars");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.ManualControlEntity", b =>
                {
                    b.Property<int>("ControlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ControlId"));

                    b.Property<string>("ControlAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ControlName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ControlValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ControlId");

                    b.ToTable("monitor_ManualControls");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.MonitorRecordEntity", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RecordTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("RecordValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("VarName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VarNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RecordId");

                    b.ToTable("monitor_MonitorRecords");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.SysUserEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("monitor_SysUsers");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.VarAlarmConfEntity", b =>
                {
                    b.Property<string>("ConfNum")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AlarmContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CompareValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VarNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ConfNum");

                    b.ToTable("monitor_VarAlarmConfs");
                });
#pragma warning restore 612, 618
        }
    }
}
