// <auto-generated />
using System;
using IndustrialMonitor.DBAcess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndustrialMonitor.DBAcess.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20260713173619_AddMonitorTables")]
    partial class AddMonitorTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IndustrialMonitor.DataEntities.AirRankingEntity", b =>
                {
                    b.Property<int>("RankingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RankingId"));

                    b.Property<double>("FinishedValue")
                        .HasColumnType("double");

                    b.Property<double>("PlanValue")
                        .HasColumnType("double");

                    b.Property<string>("WorkshopName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RankingId");

                    b.ToTable("monitor_AirRankings");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.ComponentEntity", b =>
                {
                    b.Property<int>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ComponentId"));

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Height")
                        .HasColumnType("double");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Width")
                        .HasColumnType("double");

                    b.HasKey("ComponentId");

                    b.ToTable("monitor_Components");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.DeviceAlarmEntity", b =>
                {
                    b.Property<string>("AlarmNum")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AlarmContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AlarmValue")
                        .HasColumnType("longtext");

                    b.Property<string>("ConfNum")
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RecordTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SolveTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("VarName")
                        .HasColumnType("longtext");

                    b.Property<string>("VarNum")
                        .HasColumnType("longtext");

                    b.HasKey("AlarmNum");

                    b.ToTable("monitor_DeviceAlarms");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.DeviceEntity", b =>
                {
                    b.Property<string>("DeviceNum")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ComponentId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FlowDirection")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("double");

                    b.Property<int>("Rotate")
                        .HasColumnType("int");

                    b.Property<double>("Width")
                        .HasColumnType("double");

                    b.Property<double>("X")
                        .HasColumnType("double");

                    b.Property<double>("Y")
                        .HasColumnType("double");

                    b.Property<double>("Z")
                        .HasColumnType("double");

                    b.HasKey("DeviceNum");

                    b.ToTable("monitor_Devices");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.DevicePropEntity", b =>
                {
                    b.Property<int>("DevicePropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DevicePropId"));

                    b.Property<string>("DeviceNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PropName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PropValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DevicePropId");

                    b.ToTable("monitor_DeviceProps");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.DeviceVarEntity", b =>
                {
                    b.Property<string>("VarNum")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DeviceNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Modulus")
                        .HasColumnType("double");

                    b.Property<double>("Offset")
                        .HasColumnType("double");

                    b.Property<string>("VarAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VarName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VarType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("VarNum");

                    b.ToTable("monitor_DeviceVars");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.DeviceWarningEntity", b =>
                {
                    b.Property<int>("WarningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WarningId"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("WarningId");

                    b.ToTable("monitor_DeviceWarnings");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.ManualControlEntity", b =>
                {
                    b.Property<int>("ControlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ControlId"));

                    b.Property<string>("ControlAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ControlName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ControlValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ControlId");

                    b.ToTable("monitor_ManualControls");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.MonitorRecordEntity", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AlarmNum")
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RecordTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("RecordValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("VarName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VarNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RecordId");

                    b.ToTable("monitor_MonitorRecords");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.MonitorSettingEntity", b =>
                {
                    b.Property<int>("SettingNum")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VarNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SettingNum");

                    b.ToTable("monitor_MonitorSettings");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.PropEntity", b =>
                {
                    b.Property<int>("PropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PropId"));

                    b.Property<string>("PropName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PropTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PropType")
                        .HasColumnType("int");

                    b.HasKey("PropId");

                    b.ToTable("monitor_Properties");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.SevenAirEntity", b =>
                {
                    b.Property<int>("AirId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AirId"));

                    b.Property<decimal>("Air")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AirId");

                    b.ToTable("monitor_SevenAirs");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.SevenLeakEntity", b =>
                {
                    b.Property<int>("LeakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LeakId"));

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Leak")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("LeakId");

                    b.ToTable("monitor_SevenLeaks");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.SevenPowerEntity", b =>
                {
                    b.Property<int>("PowerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PowerId"));

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Power")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("PowerId");

                    b.ToTable("monitor_SevenPowers");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.SysUserEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Gender")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("monitor_SysUsers");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.TrendAxisEntity", b =>
                {
                    b.Property<string>("AxisNum")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsShowSeperator")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsShowTitle")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LabelFormater")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Maximum")
                        .HasColumnType("double");

                    b.Property<double>("Minimum")
                        .HasColumnType("double");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrendNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AxisNum");

                    b.ToTable("monitor_TrendAxises");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.TrendEntity", b =>
                {
                    b.Property<string>("TrendNum")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsShowLegend")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TrendName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TrendNum");

                    b.ToTable("monitor_Trends");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.TrendSectionEntity", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<string>("AxisNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.HasKey("SectionId");

                    b.ToTable("monitor_TrendSections");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.TrendSeriesEntity", b =>
                {
                    b.Property<int>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SeriesId"));

                    b.Property<string>("ANum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrendNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VarNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SeriesId");

                    b.ToTable("monitor_TrendSerieses");
                });

            modelBuilder.Entity("IndustrialMonitor.DataEntities.VarAlarmConfEntity", b =>
                {
                    b.Property<string>("ConfNum")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AlarmContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CompareValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VarNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ConfNum");

                    b.ToTable("monitor_VarAlarmConfs");
                });
#pragma warning restore 612, 618
        }
    }
}
